name: Deploy on production
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy by SSH to production environment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_SSH_HOST }}
          username: ${{ secrets.PRODUCTION_SSH_USERNAME }}
          password: ${{ secrets.PRODUCTION_SSH_PASSWORD }}
          port: ${{ secrets.PRODUCTION_SSH_PORT }}
          script: |
            cd /home/mishealth/BD-Core-FHIR-IG
            git pull origin main
            rsync -av output/ /var/www/html
            docker run --rm -v $(pwd):/home/publisher/ig hl7fhir/ig-publisher-base:latest /home/publisher/ig/_genonce.sh
            sudo systemctl restart nginx